// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// MRAID_CPP
SEXP MRAID_CPP(SEXP betaxin, SEXP betayin, SEXP Sigma1sin, SEXP Sigma2sin, SEXP samplen1, SEXP samplen2, SEXP Gibbsnumberin, SEXP burninproportion, SEXP initial_betain, SEXP pi_beta_shape_in, SEXP pi_beta_scale_in, SEXP pi_c_shape_in, SEXP pi_c_scale_in, SEXP pi_1_shape_in, SEXP pi_1_scale_in, SEXP pi_0_shape_in, SEXP pi_0_scale_in);
RcppExport SEXP _MRAID_MRAID_CPP(SEXP betaxinSEXP, SEXP betayinSEXP, SEXP Sigma1sinSEXP, SEXP Sigma2sinSEXP, SEXP samplen1SEXP, SEXP samplen2SEXP, SEXP GibbsnumberinSEXP, SEXP burninproportionSEXP, SEXP initial_betainSEXP, SEXP pi_beta_shape_inSEXP, SEXP pi_beta_scale_inSEXP, SEXP pi_c_shape_inSEXP, SEXP pi_c_scale_inSEXP, SEXP pi_1_shape_inSEXP, SEXP pi_1_scale_inSEXP, SEXP pi_0_shape_inSEXP, SEXP pi_0_scale_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type betaxin(betaxinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betayin(betayinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sigma1sin(Sigma1sinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sigma2sin(Sigma2sinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type samplen1(samplen1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type samplen2(samplen2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gibbsnumberin(GibbsnumberinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type burninproportion(burninproportionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initial_betain(initial_betainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_shape_in(pi_beta_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_scale_in(pi_beta_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_c_shape_in(pi_c_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_c_scale_in(pi_c_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_1_shape_in(pi_1_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_1_scale_in(pi_1_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_0_shape_in(pi_0_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_0_scale_in(pi_0_scale_inSEXP);
    rcpp_result_gen = Rcpp::wrap(MRAID_CPP(betaxin, betayin, Sigma1sin, Sigma2sin, samplen1, samplen2, Gibbsnumberin, burninproportion, initial_betain, pi_beta_shape_in, pi_beta_scale_in, pi_c_shape_in, pi_c_scale_in, pi_1_shape_in, pi_1_scale_in, pi_0_shape_in, pi_0_scale_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MRAID_MRAID_CPP", (DL_FUNC) &_MRAID_MRAID_CPP, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRAID(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
