# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MRAID
#' 
#' @export
MRAID_CPP <- function(betaxin, betayin, Sigma1sin, Sigma2sin, samplen1, samplen2, Gibbsnumberin, burninproportion, initial_betain, pi_beta_shape_in, pi_beta_scale_in, pi_c_shape_in, pi_c_scale_in, pi_1_shape_in, pi_1_scale_in, pi_0_shape_in, pi_0_scale_in, maxvarin, alphain) {
    .Call(`_MRAID_MRAID_CPP`, betaxin, betayin, Sigma1sin, Sigma2sin, samplen1, samplen2, Gibbsnumberin, burninproportion, initial_betain, pi_beta_shape_in, pi_beta_scale_in, pi_c_shape_in, pi_c_scale_in, pi_1_shape_in, pi_1_scale_in, pi_0_shape_in, pi_0_scale_in, maxvarin, alphain)
}

